namespace Pkcs11Wrapper.Admin.Application.Models;

public sealed record AdminSessionSnapshot(
    Guid SessionId,
    Guid DeviceId,
    string DeviceName,
    nuint SlotId,
    bool IsReadWrite,
    string State,
    string SessionFlags,
    nuint DeviceError,
    bool IsUserAuthenticated,
    bool IsSecurityOfficerAuthenticated,
    DateTimeOffset OpenedUtc,
    DateTimeOffset LastTouchedUtc,
    string LastOperation,
    bool IsHealthy,
    string? Notes,
    string HealthLabel,
    string? InvalidationReason,
    bool CanLogin,
    bool CanLogout,
    bool CanCancel,
    bool CanCloseTracked,
    bool CanCloseSlot);
