#!/usr/bin/env bash

set -euo pipefail

lab_root="${SOFTHSM_LAB_ROOT:-/opt/pkcs11/softhsm}"
config_path="${SOFTHSM2_CONF:-$lab_root/softhsm2.conf}"
token_dir="${SOFTHSM_TOKEN_DIR:-$lab_root/tokens}"
module_path="${PKCS11_MODULE_PATH:-/opt/pkcs11/lib/libsofthsm2.so}"
token_label="${SOFTHSM_TOKEN_LABEL:-Pkcs11Wrapper CI Token}"
user_pin="${SOFTHSM_USER_PIN:-123456}"
so_pin="${SOFTHSM_SO_PIN:-12345678}"
aes_label="${SOFTHSM_AES_LABEL:-ci-aes}"
aes_id_hex="${SOFTHSM_AES_ID_HEX:-A1}"
rsa_label="${SOFTHSM_RSA_LABEL:-ci-rsa}"
rsa_id_hex="${SOFTHSM_RSA_ID_HEX:-B2}"

if_missing=false
reset=false
list_only=false

usage() {
  cat <<'EOF'
Usage: seed-token.sh [--if-missing] [--reset] [--list-only]

  --if-missing  Seed only when the token label is absent.
  --reset       Delete the current lab token store before recreating it.
  --list-only   Print the current object listing without modifying the token.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --if-missing)
      if_missing=true
      ;;
    --reset)
      reset=true
      ;;
    --list-only)
      list_only=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

ensure_config() {
  mkdir -p "$(dirname "$config_path")" "$token_dir"

  if [[ ! -f "$config_path" ]]; then
    cat >"$config_path" <<EOF
# Generated by the Docker Compose SoftHSM lab helper.
directories.tokendir = $token_dir
objectstore.backend = file
slots.removable = false
EOF
  fi
}

token_exists() {
  softhsm2-util --show-slots 2>/dev/null | awk -F: -v label="$token_label" '
    /Token label/ {
      value=$2
      sub(/^[ \t]+/, "", value)
      sub(/[ \t]+$/, "", value)
      if (value == label) {
        found=1
      }
    }
    END {
      exit found ? 0 : 1
    }'
}

object_exists() {
  local object_label="$1"
  pkcs11-tool --module "$module_path" --token-label "$token_label" --login --pin "$user_pin" --list-objects 2>/dev/null \
    | awk -F': ' -v label="$object_label" '
        /label:/ {
          value=$2
          sub(/^[ \t]+/, "", value)
          sub(/[ \t]+$/, "", value)
          if (value == label) {
            found=1
          }
        }
        END {
          exit found ? 0 : 1
        }'
}

list_objects() {
  pkcs11-tool --module "$module_path" --token-label "$token_label" --login --pin "$user_pin" --list-objects
}

ensure_config

if [[ "$list_only" == "true" ]]; then
  list_objects
  exit 0
fi

if [[ "$reset" == "true" ]]; then
  printf 'Resetting SoftHSM lab token store under %s\n' "$token_dir"
  find "$token_dir" -mindepth 1 -delete
fi

if token_exists; then
  if [[ "$if_missing" == "true" ]]; then
    printf 'SoftHSM token "%s" already exists; skipping re-initialization.\n' "$token_label"
  fi
else
  printf 'Initializing SoftHSM token "%s"\n' "$token_label"
  softhsm2-util --init-token --free --label "$token_label" --so-pin "$so_pin" --pin "$user_pin"
fi

if ! object_exists "$aes_label"; then
  printf 'Generating AES key "%s" (%s)\n' "$aes_label" "$aes_id_hex"
  pkcs11-tool --module "$module_path" --token-label "$token_label" --login --pin "$user_pin" \
    --keygen --key-type AES:32 --label "$aes_label" --id "$aes_id_hex" --usage-decrypt --usage-wrap >/dev/null
fi

if ! object_exists "$rsa_label"; then
  printf 'Generating RSA keypair "%s" (%s)\n' "$rsa_label" "$rsa_id_hex"
  pkcs11-tool --module "$module_path" --token-label "$token_label" --login --pin "$user_pin" \
    --keypairgen --key-type rsa:2048 --label "$rsa_label" --id "$rsa_id_hex" --usage-sign >/dev/null
fi

printf 'SoftHSM lab token ready. Current objects:\n'
list_objects
