#!/usr/bin/env bash

set -euo pipefail

command="${1:-serve}"
if [[ $# -gt 0 ]]; then
  shift
fi

lab_root="${SOFTHSM_LAB_ROOT:-/opt/pkcs11/softhsm}"
config_path="${SOFTHSM2_CONF:-$lab_root/softhsm2.conf}"
token_dir="${SOFTHSM_TOKEN_DIR:-$lab_root/tokens}"

ensure_config() {
  mkdir -p "$(dirname "$config_path")" "$token_dir"

  if [[ ! -f "$config_path" ]]; then
    cat >"$config_path" <<EOF
# Generated by the Docker Compose SoftHSM lab helper.
directories.tokendir = $token_dir
objectstore.backend = file
slots.removable = false
EOF
  fi
}

ensure_config

case "$command" in
  serve)
    if [[ "${SOFTHSM_AUTO_SEED:-1}" == "1" ]]; then
      /opt/pkcs11-lab/scripts/seed-token.sh --if-missing
    else
      printf 'SOFTHSM_AUTO_SEED disabled; leaving token provisioning to manual commands.\n'
    fi

    printf 'SoftHSM lab service is ready. SOFTHSM2_CONF=%s\n' "$config_path"
    exec sleep infinity
    ;;
  seed-token)
    exec /opt/pkcs11-lab/scripts/seed-token.sh "$@"
    ;;
  show-objects)
    exec /opt/pkcs11-lab/scripts/seed-token.sh --list-only
    ;;
  sh|bash)
    exec "$command" "$@"
    ;;
  *)
    exec "$command" "$@"
    ;;
esac
